parserOptions:
  ecmaVersion: 6
  project: ./tsconfig.json

env:
  node: true

extends:
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended

rules:
  import/prefer-default-export: off
